apiVersion: apps/v1
kind: Deployment
metadata:
  name: syvora-depl
  labels:
    app: syvora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syvora
  template:
    metadata:
      labels:
        app: syvora
    spec:
      containers:
      - name: syvora
        image: trideepnandi/syvora
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: syvora-service
spec:
  selector:
    app: syvora
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syvora-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: syvora.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syvora-service
                port:
                  number: 8000